"""empty message

Revision ID: 082d1cf297ca
Revises: fb9abbbd8bb2
Create Date: 2021-11-07 18:10:13.884720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '082d1cf297ca'
down_revision = 'fb9abbbd8bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SUBMISSIONS', sa.Column('page', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SUBMISSIONS', 'page')

    # ### end Alembic commands ###
