"""empty message

Revision ID: 1942315c8849
Revises: f7f36ac50b19
Create Date: 2022-01-01 23:41:09.029393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1942315c8849'
down_revision = 'f7f36ac50b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS',
    sa.Column('eid', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('other_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('organization', sa.String(length=30), nullable=True),
    sa.Column('right', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('eid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('TASKS',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.Column('course_title', sa.String(length=50), nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('eid_fk', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['eid_fk'], ['USERS.eid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('SUBMISSIONS',
    sa.Column('submission_id', sa.String(length=20), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('overall_similarity', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_id_FK', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id_FK'], ['TASKS.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('DOCUMENTS',
    sa.Column('document_id', sa.String(length=20), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_path', sa.String(length=255), nullable=False),
    sa.Column('submission_id_FK', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['submission_id_FK'], ['SUBMISSIONS.submission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('PAGES',
    sa.Column('page_id', sa.String(length=20), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=False),
    sa.Column('page_path', sa.String(length=255), nullable=False),
    sa.Column('submission_id_FK', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['submission_id_FK'], ['SUBMISSIONS.submission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('CONTENTS',
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.String(length=20), nullable=False),
    sa.Column('content_value', sa.Text(), nullable=False),
    sa.Column('position_x1', sa.Float(), nullable=False),
    sa.Column('position_x2', sa.Float(), nullable=False),
    sa.Column('position_y1', sa.Float(), nullable=False),
    sa.Column('position_y2', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('page_id_FK', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['page_id_FK'], ['PAGES.page_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('SOURCES',
    sa.Column('sources_id', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('similarity', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('content_id_FK', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['content_id_FK'], ['CONTENTS.content_id'], ),
    sa.PrimaryKeyConstraint('sources_id')
    )
    op.drop_table('pages')
    op.drop_table('tasks')
    op.drop_index('email', table_name='users')
    op.drop_table('users')
    op.drop_table('documents')
    op.drop_table('submissions')
    op.drop_table('sources')
    op.drop_table('contents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('content_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('content_value', mysql.TEXT(), nullable=False),
    sa.Column('position_x1', mysql.FLOAT(), nullable=False),
    sa.Column('position_x2', mysql.FLOAT(), nullable=False),
    sa.Column('position_y1', mysql.FLOAT(), nullable=False),
    sa.Column('confidence', mysql.FLOAT(), nullable=False),
    sa.Column('page_id_FK', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('position_y2', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['page_id_FK'], ['pages.page_id'], name='contents_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sources',
    sa.Column('sources_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('origin', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('similarity', mysql.FLOAT(), nullable=False),
    sa.Column('content_id_FK', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['content_id_FK'], ['contents.content_id'], name='sources_ibfk_1'),
    sa.PrimaryKeyConstraint('sources_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('submissions',
    sa.Column('submission_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('author_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('overall_similarity', mysql.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('modified_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('task_id_FK', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id_FK'], ['tasks.task_id'], name='submissions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('documents',
    sa.Column('document_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('document_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('document_path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('submission_id_FK', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['submission_id_FK'], ['submissions.submission_id'], name='documents_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('eid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('other_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('organization', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('right', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('eid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'users', ['email'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('course_title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('task_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=False),
    sa.Column('due_date', mysql.DATETIME(), nullable=False),
    sa.Column('modified_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('eid_fk', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['eid_fk'], ['users.eid'], name='tasks_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pages',
    sa.Column('page_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('page_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('page_path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('submission_id_FK', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['submission_id_FK'], ['submissions.submission_id'], name='pages_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('SOURCES')
    op.drop_table('CONTENTS')
    op.drop_table('PAGES')
    op.drop_table('DOCUMENTS')
    op.drop_table('SUBMISSIONS')
    op.drop_table('TASKS')
    op.drop_table('USERS')
    # ### end Alembic commands ###
