"""empty message

Revision ID: 8f09b6347e5c
Revises: 082d1cf297ca
Create Date: 2021-12-04 21:50:35.082991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f09b6347e5c'
down_revision = '082d1cf297ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CONTENTS', sa.Column('position_y2', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CONTENTS', 'position_y2')