"""empty message

Revision ID: f76764b1039c
Revises: 8f09b6347e5c
Create Date: 2021-12-05 23:03:20.250932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f76764b1039c'
down_revision = '8f09b6347e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USERS', sa.Column('right', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USERS', 'right')