"""empty message

Revision ID: f7f36ac50b19
Revises: f76764b1039c
Create Date: 2021-12-16 16:18:27.706538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7f36ac50b19'
down_revision = 'f76764b1039c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PAGES', sa.Column('image_base64', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PAGES', 'image_base64')

